server.port=8080

# Connect to MONGO_DB Database
spring.data.mongodb.uri=mongodb://localhost:27017/flownic

# GMAIL SMTP 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=revolixstudio.flownic@gmail.com
spring.mail.password=ldmzajqnyyicexov

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.debug=true

# Enable mail
app.mail.enabled=true

# JWT for main app
app.jwt.secret=flownic@2026
app.jwt.expiration-ms=86400000

# JWT for email verification
app.jwt.verify-secret=flownic@email@123
app.jwt.verify-expiration-ms=86400000

app.client.base-url=http://localhost:3000
app.jwt.cookie-name=auth_token
app.jwt.cookie-secure=false
